# .github/workflows/parent.yml
name: Parent Workflow

on:
  push:
    branches:
      - main

jobs:
  trigger-child:
    uses: ./.github/workflows/parent.yml
    with:
      name: welcome github actions
